spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

jwt:
  secret: UnimateTeam10SpringProjectSecretKeyForJsonWebTokenGeneration-DEV
  access-token-expiration: 3600000 # 개발용 1시간
  refresh-token-expiration: 604800000 # 개발용 7일