spring:
  datasource:
    url: jdbc:h2:file:./data/unimate;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: rlacogus06090@gmail.com         # 발신 Gmail
    password: aykzzjbpoxckidzf   # 앱 비번: 공백 없이 16자
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

jwt:
  secret: "unimate-super-long-secret-32chars-min-please!!!!!"
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000

logging:
  level:
    com.unimate.global.ws: DEBUG
    com.unimate.global.jwt: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    com.unimate: DEBUG

server:
  port: 8080
