name: "🛠 Refactor"
description: "코드 품질 개선, 구조 변경, 중복 제거 등 리팩터링 작업 이슈"
labels: ["refactor"]
body:
  - type: textarea
    attributes:
      label: 리팩터링 대상
      description: 어떤 코드/모듈/구조를 리팩터링하려는지 작성해주세요.
      placeholder: 예) ItemService 클래스의 중복 로직 제거
    validations:
      required: true

  - type: textarea
    attributes:
      label: 리팩터링 필요성
      description: 왜 이 리팩터링이 필요한지, 어떤 문제가 있는지 작성해주세요.
      placeholder: 예) 중복된 로직이 많아 유지보수성이 떨어집니다.
    validations:
      required: true




